### ISSUE TITLE
how is it installed?

### ISSUE THREAD

**Issue by demianrey** [aliyilmaz/ipscanner#1]
Hi , I'm very interested in this project but it doesn't say how it is installed or how it works, please help
Thanks and greetings

**Comment by aliyilmaz** [comment]
Hello, give write permission to your server when you extract it, then you can use it through the interface.

**Comment by demianrey** [comment]
can i do it locally? for example on an Android cell phone

**Comment by aliyilmaz** [comment]
> can i do it locally? for example on an Android cell phone
> Edit. I'm already running it on Android, but I get this with every test
> ![Screenshot_20210722-180126](https://user-images.githubusercontent.com/48655207/126719625-db2962f7-be75-45b4-aec1-177f1acc1cd3.jpg)
> 
> This is correct?

Hello Yes, now you can check the files created with http code in the same directory.

**Comment by demianrey** [comment]
it works perfect, it's just what I needed ... But if you added  support for text file and cdir it's amazing, I invite you a coffee. This is my telegram @demianrey. Thank you very much for your work

**Comment by aliyilmaz** [comment]
> it works perfect, it's just what I needed ... But if you added support for text file and cdir it's amazing, I invite you a coffee. This is my telegram @demianrey. Thank you very much for your work

I'm so glad to hear it. By the way, I have included the methods in the [ipscanner](https://github.com/aliyilmaz/ipscanner/) in the framework I am developing, you can examine it from there if you want. [getAddressCode()](https://github.com/aliyilmaz/Mind/blob/master/src/Mind.php#L3572), [addressGenerator()](https://github.com/aliyilmaz/Mind/blob/master/src/Mind.php#L3641)

Kind Regards.
